Initial infraestructure refactor
eProsima/Fast-DDS-QoS-Profiles-Manager pull request #38
Opened 2023-04-11 12:13 UTC by JesusPoderoso

- API pending refactor
- New Exception and its usage
- Util classes renamed

2023-04-11 12:18 UTC, JesusPoderoso commented on lib/include/fastdds_qos_profiles_manager/transport_descriptor/TransportDescriptor.hpp
> + * @param[in] index Collection element to be printed. If empty, the complete collection is erased.
```suggestion
 * @param[in] index Collection element to be removed. If empty, the complete collection is erased.
```

2023-04-11 12:18 UTC, JesusPoderoso commented on lib/include/fastdds_qos_profiles_manager/transport_descriptor/TransportDescriptor.hpp
> + * @param[in] index Collection element to be printed. If empty, the complete collection is erased.
```suggestion
 * @param[in] index Collection element to be removed. If empty, the complete collection is erased.
```

2023-04-11 12:18 UTC, JesusPoderoso commented on lib/include/fastdds_qos_profiles_manager/transport_descriptor/TransportDescriptor.hpp
> + * @param[in] index Collection element to be printed. If empty, the complete collection is erased.
```suggestion
 * @param[in] index Collection element to be removed. If empty, the complete collection is erased.
```

2023-04-11 12:18 UTC, JesusPoderoso commented on lib/include/fastdds_qos_profiles_manager/transport_descriptor/TransportDescriptor.hpp
> + * @param[in] index Collection element to be printed. If empty, the complete collection is erased.
```suggestion
 * @param[in] index Collection element to be removed. If empty, the complete collection is erased.
```

2023-04-11 12:18 UTC, JesusPoderoso commented on lib/src/cpp/utils/XMLManager.hpp
> +    /**
This was no longer public, so moved to private method.

2023-04-11 12:42 UTC, JLBuenoLopez-eProsima commented on lib/include/fastdds_qos_profiles_manager/domain_participant/DomainParticipant.hpp
> + * @param[in] index Collection element to be printed. If empty, the complete collection is erased.
True. Copy/paste has its risks :sweat_smile:

2023-04-11 13:37 UTC, JLBuenoLopez-eProsima requested changes

2023-04-11 13:37 UTC, JLBuenoLopez-eProsima commented on lib/src/cpp/utils/ErrorHandlerXMLManager.hpp
> +#ifndef _FAST_DDS_QOS_PROFILES_MANAGER_UTILS_XML_MANAGER_ERROR_HANDLER_HPP_
You have altered the order. It should be:

```suggestion
#ifndef _FAST_DDS_QOS_PROFILES_MANAGER_UTILS_ERROR_HANDLER_XML_MANAGER_HPP_
```

2023-04-11 13:37 UTC, JLBuenoLopez-eProsima commented on lib/src/cpp/utils/TagsXMLManager.hpp
> +#ifndef _FAST_DDS_QOS_PROFILES_MANAGER_UTILS_XML_MANAGER_TAGS_HPP_
Same comment again.

2023-04-12 05:06 UTC, JLBuenoLopez-eProsima approved these changes
LGTM

2023-04-12 05:06 UTC, merged